### ISSUE TITLE
 throw new Error('A remote endpoint is required for a network layer')

### ISSUE THREAD

**Issue by veeramarni** [drejohnson/react-universal-typescript#1]
I was looking for similar project to run our app. Have it running successfully for you, i'm getting following error. 

```
react-universal-typescript/node_modules/apollo-client/apollo.umd.js:35
            throw new Error('A remote endpoint is required for a network layer');
            ^

Error: A remote endpoint is required for a network layer

```

**Comment by veeramarni** [comment]
I have setup .env file with required setting pointing to `graphcool` which at least resolved above error but since schema don't exist in `graphcool` it is failing related to it. I'm closing this.

**Comment by drejohnson** [comment]
I missed this.

If you want to try it with my mock schema add this endpoint: `https://api.graph.cool/simple/v1/cixm67lmh1yjd0177j5cwt47t`
